---
title: "CTmax_Analysis"
author: "Terra Dressler"
date: "2024-05-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning =F, message=F)
```

#### Libraries
```{r}

library(tidyverse)
library(car)
library(FSA)

```

#### Lower Deschutes CTmax
```{r}

#Step 1: read in data, get means and SEMs

CT_LD <- read_csv("CTmax_LowerDeschutes.csv")  %>% 
  mutate(population="Lower Deschutes")

CT_LD_sum<- CT_LD %>% 
  group_by(treatment) %>% 
  summarise(mean_CT = mean(ctmax), sem = sd(ctmax)/sqrt(n()), min = min(ctmax), max = max(ctmax))

#Step 2: Plot

ggplot(CT_LD, aes(x = treatment, y = ctmax, color = as.factor(treatment)))+
geom_pointrange(data= CT_LD_sum, aes(y = mean_CT, x=treatment, ymin=mean_CT-sem, ymax=mean_CT+sem), size =1)+
  geom_point(size = 2, alpha = 0.8)+
  scale_y_continuous(limits = c(27, 33),breaks=c(27,28, 29,30,31,32,33))+
  scale_color_manual(values = c("#FEE391", "#EC7014" ,"#993404"))+
  theme_classic()+
  theme(text = element_text(size = 17), aspect.ratio = 1, legend.position = "none")

#Step 3: Statistics

qqPlot(CT_LD$ctmax)
hist(CT_LD$ctmax)
shapiro.test(CT_LD$ctmax) #not a normal dist

leveneTest(ctmax~treatment, data = CT_LD) #equal var

#N>30, applying Critical Limit Theorem

summary(aov(ctmax~treatment, data = CT_LD)) #significant differences between treatments

TukeyHSD(aov(ctmax~treatment, data = CT_LD)) #ambient CTmax significantly greater (~1C) than the other 2

kruskal.test(ctmax~treatment, data = CT_LD)
dunnTest(ctmax~treatment, data = CT_LD) #same result with non-parametric test

```


#### John Day CTmax
```{r}

#Step 1: read in data, get means and SEMs

CT_JD <- read_csv("CTmax_JohnDay.csv")%>% 
  mutate(population="John Day")



CT_JD_sum<- CT_JD %>% 
  group_by(treatment) %>% 
  summarise(mean_CT = mean(ctmax), sem = sd(ctmax)/sqrt(n()), min = min(ctmax), max = max(ctmax))

#Step 2: Plot

ggplot(CT_JD, aes(x = treatment, y = ctmax, color = as.factor(treatment)))+
geom_pointrange(data= CT_JD_sum, aes(y = mean_CT, x=treatment, ymin=mean_CT-sem, ymax=mean_CT+sem), size =1)+
  geom_point(size = 2, alpha = 0.8)+
  scale_y_continuous(limits = c(27, 33),breaks=c(27,28, 29,30,31,32,33))+
  scale_color_manual(values = c("#FCC5C0", "#980043"))+
  theme_classic()+
  theme(text = element_text(size = 17), aspect.ratio = 1, legend.position = "none")

#Step 3: Statistics

qqPlot(CT_JD$ctmax)
shapiro.test(CT_JD$ctmax) #normal distribution

var.test(ctmax~as.factor(treatment), data = CT_JD) #equal variance

t.test(ctmax~as.factor(treatment), data = CT_JD, var.equal = TRUE) #no significant difference between CTmax of ambient (14-27C) vs hot (23-27C).

```


#### North Umpqua CTmax
```{r}

#Step 1: read in data, get means and SEMs
CT_NA <- read_csv("CTmax_NorthUmpqua.csv") %>% 
  mutate(population="North Umpqua")


CT_NA_sum <- CT_NA %>% 
  group_by(treatment) %>% 
  summarise(mean_CT = mean(ctmax), sem = sd(ctmax)/sqrt(n()))

#Step 2: Plot

ggplot(CT_NA, aes(x = treatment, y = ctmax,color = as.factor(treatment)))+
  geom_pointrange(data= CT_NA_sum, aes(y = mean_CT, x=treatment, ymin=mean_CT-sem, ymax=mean_CT+sem), size =1)+
   geom_point(size = 2, alpha = 0.8)+
  scale_y_continuous(limits = c(27, 33),breaks=c(27,28, 29,30,31,32,33))+
  scale_color_manual(values = c("#C6DBEF", "#6BAED6","#2171B5", "#08306B"))+
  theme_classic()+
  theme(text = element_text(size = 17), aspect.ratio = 1, legend.position = "none")

#Step 3: Statistics

qqPlot(CT_NA$ctmax)
shapiro.test(CT_NA$ctmax) #not normal dist

leveneTest(ctmax~treatment, data = CT_NA) #equal var

#N>30, applying Critical Limit Theorem
 
summary(aov(ctmax~treatment, data = CT_NA)) #no significant differences between CTmax at different temps

kruskal.test(ctmax~treatment, data = CT_NA) #same result with non-parametric test

```


#### Siletz CTmax
```{r}

#Step 1: read in data, get means and SEMs
CT_S <- read_csv("CTmax_Siletz.csv") %>% 
  mutate(population="Siletz")


CT_S_sum <- CT_S %>% 
  group_by(treatment) %>% 
  summarise(mean_CT = mean(ctmax), sem = sd(ctmax)/sqrt(n()))

#Step 2: Plot

ggplot(CT_S, aes(x = treatment, y = ctmax, color = as.factor(treatment)))+
geom_pointrange(data= CT_S_sum, aes(y = mean_CT, x=treatment, ymin=mean_CT-sem, ymax=mean_CT+sem), size =1)+
   geom_point(size = 2, alpha = 0.8)+
  scale_y_continuous(limits = c(27, 33),breaks=c(27,28, 29,30,31,32,33))+
  scale_color_manual(values = c("#CCECE6",  "#66C2A4","#238B45"))+
  theme_classic()+
  theme(text = element_text(size = 17), aspect.ratio = 1, legend.position = "none")

#Step 3: Statistics

qqPlot(CT_S$ctmax)
shapiro.test(CT_S$ctmax) #normal dist

leveneTest(ctmax~as.factor(treatment), data = CT_S) #equal var

aov_CT_S <- aov(ctmax~as.factor(treatment), data = CT_S)
summary(aov_CT_S)

TukeyHSD(aov_CT_S) #CTmax increased with each increase in holding temperatures


```


#Population Comparisons


```{r}

#Compare common temperature treatments - all populations

#20-24C treatment, aerobic scope measured at 22C
CT_22 <- rbind(CT_LD, CT_JD, CT_NA, CT_S) %>% 
  filter(mmr_temp==22)

ggplot(CT_22, aes(x = population, y = ctmax, fill = population))+
  geom_boxplot(width = 0.4, size =1)+
  geom_point(size = 3, alpha = 0.6)+
  scale_y_continuous(limits = c(27, 32))+
  scale_fill_manual(values = c("#EC7014","#2171B5","#238B45"))+
  theme_classic()+
  theme(text = element_text(size = 12), aspect.ratio = 1, legend.position = "none")

qqPlot(CT_22$ctmax)
shapiro.test(CT_22$ctmax) #normal distribution

leveneTest(ctmax~population, data=CT_22) #unequal variance

kruskal.test(ctmax~population, data=CT_22) #significant differences in CTmax between populations 

dunnTest(ctmax~population, data=CT_22) #Lower Deschutes has a significantly higher CTmax for this temp treatment

#18-22C temperature treatment, aerobic scope measured at 19 (for John Day temp treatment was 14-27C)

CT_19 <- rbind(CT_LD, CT_NA, CT_S) %>% 
  filter(mmr_temp==19)

ggplot(CT_19, aes(x = population, y = ctmax, fill = population))+
  geom_boxplot(width = 0.4, size =1)+
  geom_point(size = 3, alpha = 0.6)+
  scale_y_continuous(limits = c(27, 32))+
  scale_fill_manual(values = c("#DD3497","#EC7014","#2171B5","#238B45"))+
  theme_classic()+
  theme(text = element_text(size = 12), aspect.ratio = 1, legend.position = "none")

qqPlot(CT_19$ctmax)
shapiro.test(CT_19$ctmax) #normal distribution

leveneTest(ctmax~population, data=CT_19) #unequal variance

kruskal.test(ctmax~population, data=CT_19) #significant differences in CTmax between populations 

dunnTest(ctmax~population, data=CT_19) #Lower Deschutes has highest CTmax, followed by John Day, followed by North Umpqua and Siletz

#caveat: John Day experienced a much larger fluctuation than the rest


#Now comparing CTmax between North Umpqua and Siletz at ambient since ambient temps were the same for these 2 populations

CT_16 <-rbind(CT_NA, CT_S) %>% 
  filter(mmr_temp==16)

ggplot(CT_16, aes(x = population, y = ctmax, fill = population))+
  geom_boxplot(width = 0.4, size =1)+
  geom_point(size = 3, alpha = 0.6)+
  scale_y_continuous(limits = c(27, 32))+
  scale_fill_manual(values = c("#2171B5","#238B45"))+
  theme_classic()+
  theme(text = element_text(size = 12), aspect.ratio = 1, legend.position = "none")

qqPlot(CT_16$ctmax)
shapiro.test(CT_16$ctmax) #normal distribution

var.test(ctmax~population, data=CT_16) #unequal variance

t.test(ctmax~population, data=CT_16, var.equal=F) #North Umpqua has a higher CTmax than Siletz at ambient temps

```


