---
title: "2_Metabolic_Rate_Analysis"
author: "Terra Dressler"
date: "2024-05-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=F, echo=F)
```


#### Libraries

```{r}

library(tidyverse)
library(lme4)
library(car)
library(FSA)

```


#### Resting (or Routine) Metabolic Rate

Lower Deschutes
```{r}

#Step 1: Read in RMR data 
RMR_LD <- read_csv("RMR_LowerDeschutes.csv")


#Step 2: Plot all RMR data 

ggplot(RMR_LD, aes(x = temp, y = mean_rmr_72, col = treatment))+
  geom_jitter(size = 3, alpha = 0.8)+
   scale_color_manual(values = c("#FEE391","#EC7014","#993404"), labels=c('Ambient (18-22)', "Intermediate (20-24)", "Warm (23-27)"))+
  labs(y = expression('Resting Metabolic Rate (mg '* kg^-1* L^-1*')'), 
       x = expression('Temperature ('*~degree*C*')'))+
   theme_classic()+
  scale_x_continuous(limits = c(14, 27),breaks = c(14,16,18,20,22,24,26))+
  scale_y_continuous(limits = c(0,13), breaks = c(0,2,4,6,8,10,12))+
  theme(axis.text = element_text(size = 18, color = "black"),
        axis.title = element_text(size =17),
        legend.text = element_text(size = 12), legend.position = "right", legend.title=element_blank())

ggsave("Figure4A.png",dpi=300)


#Step 3: Statistical analysis to determine the relationship between temperature and RMR (using fish ID as a random effect to account for repeated measures within holding temperature treatments)

#start with a linear model
lmer_LD_1 <- lmer(mean_rmr_72~temp * as.factor(treatment) + (1|fish_id), data=RMR_LD, REML=FALSE) 
Anova(lmer_LD_1, type = c(3))

#trying an exponential model

lmer_LD_exp_1 <- lmer(log(mean_rmr_72)~temp * as.factor(treatment) + (1|fish_id), data=RMR_LD, REML=FALSE) 
Anova(lmer_LD_exp_1, type = c(3))

#dropping insignificant interaction between fixed effects

lmer_LD_exp_2 <- lmer(log(mean_rmr_72)~temp + as.factor(treatment) + (1|fish_id), data=RMR_LD, REML=FALSE) 
Anova(lmer_LD_exp_2, type = c(2)) #significant effects of treatment and acute temp on RMR

BIC(lmer_LD_1,lmer_LD_exp_1, lmer_LD_exp_2) #exponential model WITHOUT the interaction is the best fit

plot(lmer_LD_exp_2)
hist(resid(lmer_LD_exp_2)) #residuals normally distributed

summary(lmer_LD_exp_2)

#Step 4: RMR comparison at chase/aerobic scope temperatures
RMR_LD_chase <- RMR_LD %>% 
  filter(temp==mmr_temp)  

RMR_LD_chase_sum <- RMR_LD_chase %>% 
  group_by(temp,treatment) %>% 
  summarise(mean_RMR = mean(mean_rmr_72), sem_RMR = sd(mean_rmr_72)/sqrt(n()))

qqPlot(RMR_LD_chase$mean_rmr_72)
shapiro.test(RMR_LD_chase$mean_rmr_72) #normal distribution

leveneTest(mean_rmr_72~as.factor(temp), data = RMR_LD_chase) #equal variance

summary(aov(mean_rmr_72~as.factor(temp), data = RMR_LD_chase)) #significant differences in RMR 

TukeyHSD(aov(mean_rmr_72~as.factor(temp), data = RMR_LD_chase)) #RMR at 19C significantly lower than 22C and 26C

```

John Day
```{r}

#Step 1: Read in RMR data 
RMR_JD <- read_csv("RMR_JohnDay.csv")


#Step 2: Plot all RMR data 

ggplot(RMR_JD, aes(x = temp, y = mean_rmr_72, col = treatment))+
  geom_jitter(size = 3, alpha = 0.8)+
  scale_color_manual(values = c( "#FCC5C0", "#DD3497", "#980043"), labels=c('Ambient (14-27)', "Intermediate (20-24)", "Warm (23-27)"))+
  labs(y = expression('Resting Metabolic Rate (mg '* kg^-1* L^-1*')'), 
       x = expression('Temperature ('*~degree*C*')'))+
   theme_classic()+
  scale_x_continuous(limits = c(14, 27),breaks = c(14,16,18,20,22,24,26))+
  scale_y_continuous(limits = c(0,13), breaks = c(0,2,4,6,8,10,12))+
  theme(axis.text = element_text(size = 18, color = "black"),
        axis.title = element_text(size =17),
        legend.text = element_text(size = 12), legend.position = "right", legend.title=element_blank())

ggsave("Figure4B.png",dpi=300)

#Step 3: Statistical analysis to determine the relationship between temperature and RMR (using fish ID as a random effect to account for repeated measures within holding temperature treatments)

#start with a linear model
lmer_JD_1 <- lmer(mean_rmr_72~temp * as.factor(treatment) + (1|fish_id), data=RMR_JD, REML=FALSE) 
Anova(lmer_JD_1, type = c(3))

#dropping insignificant interaction between fixed effects
lmer_JD_2 <- lmer(mean_rmr_72~temp + as.factor(treatment) + (1|fish_id), data=RMR_JD, REML=FALSE) 
Anova(lmer_JD_2, type = c(2))

#dropping insignificant effect of temperature treatment
lmer_JD_3 <- lmer(mean_rmr_72~temp + (1|fish_id), data=RMR_JD, REML=FALSE) 
Anova(lmer_JD_3, type = c(2)) 

#trying an exponential model

lmer_JD_exp_1 <- lmer(log(mean_rmr_72)~temp * as.factor(treatment) + (1|fish_id), data=RMR_JD, REML=FALSE) 
Anova(lmer_JD_exp_1, type = c(3)) #significant effects of acute temp, treatment, and their interaction


BIC(lmer_JD_1,lmer_JD_2, lmer_JD_3,lmer_JD_exp_1) #exponential model is the best fit

plot(lmer_JD_exp_1)
hist(resid(lmer_JD_exp_1)) #residuals normally distributed

summary(lmer_JD_exp_1)

#Step 4: RMR comparison at chase/aerobic scope temperatures
RMR_JD_chase <- RMR_JD %>% 
  filter(temp==mmr_temp)  

RMR_JD_chase_sum <- RMR_JD_chase %>% 
  group_by(temp,treatment) %>% 
  summarise(mean_RMR = mean(mean_rmr_72), sem_RMR = sd(mean_rmr_72)/sqrt(n()))

hist(RMR_JD_chase$mean_rmr_74)
shapiro.test(RMR_JD_chase$mean_rmr_72) # not a normal distribution

leveneTest(mean_rmr_72~as.factor(temp), data = RMR_JD_chase) #unequal variance

kruskal.test(mean_rmr_72~as.factor(temp), data = RMR_JD_chase) #significant differences in RMR 

dunnTest(mean_rmr_72~as.factor(temp), data = RMR_JD_chase) #RMR at 19C significantly lower than 22C and 27C

```

North Umpqua
```{r}

#Step 1: Read in RMR data 
RMR_NU <- read_csv("RMR_NorthUmpqua.csv")


#Step 2: Plot all RMR data 

ggplot(RMR_NU, aes(x = temp, y = mean_rmr_72, col = treatment))+
  geom_jitter(size = 3, alpha = 0.8)+
 scale_color_manual(values = c("#C6DBEF", "#6BAED6","#2171B5", "#08306B"), labels=c('Ambient (16-19)', "Intermediate (18-22)", "Intermediate (20-24)", "Warm (23-26)"))+
  labs(y = expression('Resting Metabolic Rate (mg '* kg^-1* L^-1*')'), 
       x = expression('Temperature ('*~degree*C*')'))+
   theme_classic()+
  scale_x_continuous(limits = c(14, 27),breaks = c(14,16,18,20,22,24,26))+
  scale_y_continuous(limits = c(0,13), breaks = c(0,2,4,6,8,10,12))+
  theme(axis.text = element_text(size = 18, color = "black"),
        axis.title = element_text(size =17),
        legend.text = element_text(size = 12), legend.position = "right", legend.title=element_blank())

ggsave("Figure4C.png",dpi=300)

#Step 3: Statistical analysis to determine the relationship between temperature and RMR (using fish ID as a random effect to account for repeated measures within holding temperature treatments)

#start with a linear model
lmer_NU_1 <- lmer(mean_rmr_72~temp * as.factor(treatment) + (1|fish_id), data=RMR_NU, REML=FALSE) 
Anova(lmer_NU_1, type = c(3))

#dropping insignificant interaction between fixed effects
lmer_NU_2 <- lmer(mean_rmr_72~temp + as.factor(treatment) + (1|fish_id), data=RMR_NU, REML=FALSE) 
Anova(lmer_NU_2, type = c(2))

#trying an exponential model

lmer_NU_exp_1 <- lmer(log(mean_rmr_72)~temp * as.factor(treatment) + (1|fish_id), data=RMR_NU, REML=FALSE) 
Anova(lmer_NU_exp_1, type = c(3)) 

#dropping insignificant interaction between fixed effects

lmer_NU_exp_2 <- lmer(log(mean_rmr_72)~temp +as.factor(treatment) + (1|fish_id), data=RMR_NU, REML=FALSE) 
Anova(lmer_NU_exp_2, type = c(2)) #significant effects of acute temp and treatment

BIC(lmer_NU_1,lmer_NU_2,lmer_NU_exp_1,lmer_NU_exp_2) #exponential model with no interaction is the best fit

plot(lmer_NU_exp_2)
hist(resid(lmer_NU_exp_2)) #residuals normally distributed

summary(lmer_NU_exp_2)

#Step 4: RMR comparison at chase/aerobic scope temperatures
RMR_NU_chase <- RMR_NU %>% 
  filter(temp==mmr_temp)  

RMR_NU_chase_sum <- RMR_NU_chase %>% 
  group_by(temp,treatment) %>% 
  summarise(mean_RMR = mean(mean_rmr_72), sem_RMR = sd(mean_rmr_72)/sqrt(n()))

hist(RMR_NU_chase$mean_rmr_72)
shapiro.test(RMR_NU_chase$mean_rmr_72) # normal distribution

leveneTest(mean_rmr_72~as.factor(temp), data = RMR_NU_chase) #unequal variance

kruskal.test(mean_rmr_72~as.factor(temp), data = RMR_NU_chase) #significant differences in RMR between chase temps

dunnTest(mean_rmr_72~as.factor(temp), data = RMR_NU_chase) #RMR increases between 19 & 22

```


Siletz
```{r} 

#Step 1: Read in RMR data 
RMR_S <- read_csv("RMR_Siletz.csv")


#Step 2: Plot all RMR data 

ggplot(RMR_S, aes(x = temp, y = mean_rmr_72, col = treatment))+
  geom_jitter(size = 3, alpha = 0.8)+
 scale_color_manual(values = c("#CCECE6",  "#66C2A4","#238B45", "#00441B"), labels=c('Ambient (15-19)', "Intermediate (18-22)", "Intermediate (20-24)", "Warm (23-26)"))+
  labs(y = expression('Resting Metabolic Rate (mg '* kg^-1* L^-1*')'), 
       x = expression('Temperature ('*~degree*C*')'))+
   theme_classic()+
  scale_x_continuous(limits = c(14, 27),breaks = c(14,16,18,20,22,24,26))+
  scale_y_continuous(limits = c(0,13), breaks = c(0,2,4,6,8,10,12))+
  theme(axis.text = element_text(size = 18, color = "black"),
        axis.title = element_text(size =17),
        legend.text = element_text(size = 12), legend.position = "right", legend.title=element_blank())

ggsave("Figure4D.png",dpi=300)

#Step 3: Statistical analysis to determine the relationship between temperature and RMR (using fish ID as a random effect to account for repeated measures within holding temperature treatments)

#start with a linear model
lmer_S_1 <- lmer(mean_rmr_72~temp * as.factor(treatment) + (1|fish_id), data=RMR_S, REML=FALSE) 
Anova(lmer_S_1, type = c(3))

#trying an exponential model

lmer_S_exp_1 <- lmer(log(mean_rmr_72)~temp * as.factor(treatment) + (1|fish_id), data=RMR_S, REML=FALSE) 
Anova(lmer_S_exp_1, type = c(3)) #significant effects of acute temp and treatment and their interaction


BIC(lmer_S_1,lmer_S_exp_1) #exponential model is the best fit

plot(lmer_S_exp_1)
hist(resid(lmer_S_exp_1)) #residuals normally distributed

summary(lmer_S_exp_1)

#Step 4: RMR comparison at chase/aerobic scope temperatures
RMR_S_chase <- RMR_S %>% 
  filter(temp==mmr_temp)  

RMR_S_chase_sum <- RMR_S_chase %>% 
  group_by(temp,treatment) %>% 
  summarise(mean_RMR = mean(mean_rmr_72), sem_RMR = sd(mean_rmr_72)/sqrt(n()))

hist(RMR_S_chase$mean_rmr_72)
shapiro.test(RMR_S_chase$mean_rmr_72) # normal distribution

leveneTest(mean_rmr_72~as.factor(temp), data = RMR_S_chase) #equal variance

summary(aov(mean_rmr_72~as.factor(temp), data = RMR_S_chase)) #significant differences in RMR between chase temps

TukeyHSD(aov(mean_rmr_72~as.factor(temp), data = RMR_S_chase)) #significant differences between all temps except 19&22

```

Population Comparison: RMR during 20-24C treatment
```{r}

LD_22 <- RMR_LD %>% 
  filter(mmr_temp==22) %>%
  mutate(population = "Lower Deschutes")

JD_22 <- RMR_JD %>% 
  filter(mmr_temp==22)%>%
  mutate(population = "John Day")

NU_22 <- RMR_NU %>% 
  filter(mmr_temp==22)%>%
  mutate(population = "North Umpqua")

S_22 <- RMR_S %>% 
  filter(mmr_temp==22)%>%
  mutate(population = "Siletz")

RMR_22_All <- rbind(LD_22,JD_22,NU_22,S_22) %>%
  select(population, mmr_temp, temp,bw, mean_rmr_72)

RMR_22_sum <- RMR_22_All %>% 
  group_by(population, temp) %>% 
  summarise(mean_rmr = mean(mean_rmr_72), sem_rmr = sd(mean_rmr_72)/sqrt(n()))

ggplot(RMR_22_sum, aes(x = temp, y = mean_rmr, ymin = mean_rmr-sem_rmr, ymax=mean_rmr+sem_rmr, color = population))+
  geom_pointrange(size = 1, alpha = 0.8)+
   scale_color_manual(values = c("#DD3497","#EC7014","#2171B5", "#238B45"))+
   labs(y = expression('Resting Metabolic Rate (mg '* kg^-1* L^-1*')'), 
       x = expression('Temperature ('*~degree*C*')'))+
   theme_classic()+
 scale_x_continuous(limits = c(20, 24), breaks = c(20, 21, 22, 23, 24))+
  scale_y_continuous(limits = c(1,7))+
  theme(axis.text = element_text(size = 18, color = "black"),
        axis.title = element_text(size =17),
        legend.text = element_text(size = 9), legend.position = "right", legend.title = element_blank())

ggsave("Figure_S3.png", dpi=300, height=4, width=6)

#Are there significant differences between RMR of the different populations at each acute temperature during a common treatment?

RMR_20 <- RMR_22_All %>% 
  filter(temp ==20)

qqPlot(RMR_20$mean_rmr_72)

leveneTest(mean_rmr_72~population, data = RMR_20) # var not equal

kruskal.test(mean_rmr_72~population, data = RMR_20)

dunnTest(mean_rmr_72~population, data = RMR_20) #John Day significantly higher RMR that North Umpqua and Siletz at 20C


RMR_21 <- RMR_22_All %>% 
  filter(temp ==21)

qqPlot(RMR_21$mean_rmr_72)

leveneTest(mean_rmr_72~population, data = RMR_21) # var equal

summary(aov(mean_rmr_72~population, data = RMR_21))

TukeyHSD(aov(mean_rmr_72~population, data = RMR_21)) #John Day significantly higher RMR, Deschutes higher than Siletz but not North Umpqua at 21C


RMR_22 <- RMR_22_All %>% 
  filter(temp ==22)

qqPlot(RMR_22$mean_rmr_72)

leveneTest(mean_rmr_72~population, data = RMR_22) # var equal

summary(aov(mean_rmr_72~population, data = RMR_22))

TukeyHSD(aov(mean_rmr_72~population, data = RMR_22))  #John Day and Deschutes have significantly higher RMR than the other 2 at 22C

RMR_23 <- RMR_22_All %>% 
  filter(temp ==23)

qqPlot(RMR_23$mean_rmr_72)

leveneTest(mean_rmr_72~population, data = RMR_23) #var not equal

kruskal.test(mean_rmr_72~population, data = RMR_23)

dunnTest(mean_rmr_72~population, data = RMR_23)#John Day and Deschutes have significantly higher RMR than the other 2 at 23C

RMR_24 <- RMR_22_All %>% 
  filter(temp ==24)

qqPlot(RMR_24$mean_rmr_72)

leveneTest(mean_rmr_72~population, data = RMR_24) #equal var

summary(aov(mean_rmr_72~population, data = RMR_24))

TukeyHSD(aov(mean_rmr_72~population, data = RMR_24)) #John Day and Deschutes have significantly higher RMR than Siletz (but not North Umpqua) at 23C

```


#### Maximum Metabolic Rate (MMR)

Lower Deschutes

```{r}

#Step 1: read in MMR data, get means & SEMs
MMR_LD <- read_csv("MMR_LowerDeschutes.csv")

MMR_LD_sum <- MMR_LD %>% 
  group_by(temperature) %>% 
  summarise(mean_MMR = mean(mmr_scaled_74), sem_MMR = sd(mmr_scaled_74)/sqrt(n()))

#Step 2: plot MMR data

ggplot(MMR_LD, aes(x = as.factor(temperature) , y = mmr_scaled_74, color = as.factor(temperature))) +
  geom_boxplot(width = 0.4)+
  geom_point(size = 2.5, alpha = 0.8)+
  scale_x_discrete(name = expression("Temperature " ( degree*C)))+
   scale_color_manual(values = c( "#FEE391", "#EC7014" ,"#993404"))+
  ylab(expression(paste('MMR '(mg*O[2] * kg^-1 * min^-1))))+
  scale_y_continuous(limits= c(0, 20))+
  theme_classic()+
  theme(text =element_text(size=18, colour= 'black'),
        axis.text = element_text(size=18, colour= 'black'),
        aspect.ratio = 0.9, legend.position = "none")

#Step 3: Statistics to test for differences in MMR between temperatures

qqPlot(MMR_LD$mmr_scaled_74)

#normal distribution

leveneTest(mmr_scaled_74~as.factor(temperature), data = MMR_LD)

#equal variance

LD_MMR_aov <- aov(mmr_scaled_74~as.factor(temperature), data = MMR_LD)
summary(LD_MMR_aov)
TukeyHSD(LD_MMR_aov)

#MMR is statistically different between 19 and 22 and between 19 and 26


```

John Day
```{r}

#Step 1: read in MMR data, get means & SEMs
MMR_JD <- read_csv("MMR_JohnDay.csv")

MMR_JD_sum <- MMR_JD %>% 
  group_by(temperature) %>% 
  summarise(mean_MMR = mean(mmr_scaled_74), sem_MMR = sd(mmr_scaled_74)/sqrt(n()))

#Step 2: plot MMR data

ggplot(MMR_JD, aes(x = as.factor(temperature) , y = mmr_scaled_74, color = as.factor(temperature))) +
  geom_boxplot(width = 0.4)+
  geom_point(size = 2.5, alpha = 0.8)+
  scale_x_discrete(name = expression("Temperature " ( degree*C)))+
   scale_color_manual(values = c(  "#FCC5C0", "#DD3497", "#980043"))+
  ylab(expression(paste('MMR '(mg*O[2] * kg^-1 * min^-1))))+
  scale_y_continuous(limits= c(0, 20))+
  theme_classic()+
  theme(text =element_text(size=18, colour= 'black'),
        axis.text = element_text(size=18, colour= 'black'),
        aspect.ratio = 0.9, legend.position = "none")

#Step 3: Statistics to test for differences in MMR between temperatures

qqPlot(MMR_JD$mmr_scaled_74)

#normal distribution

leveneTest(mmr_scaled_74~as.factor(temperature), data = MMR_JD)

#equal variance

JD_MMR_aov <- aov(mmr_scaled_74~as.factor(temperature), data = MMR_JD)
summary(JD_MMR_aov)

#MMR is not statistically different between 19, 22, and 27

```

North Umpqua
```{r}

#Step 1: read in MMR data, get means & SEMs
MMR_NU <- read_csv("MMR_NorthUmpqua.csv")

MMR_NU_sum <- MMR_NU %>% 
  group_by(temperature) %>% 
  summarise(mean_MMR = mean(mmr_scaled_74), sem_MMR = sd(mmr_scaled_74)/sqrt(n()))

#Step 2: plot MMR data

ggplot(MMR_NU, aes(x = as.factor(temperature) , y = mmr_scaled_74, color = as.factor(temperature))) +
  geom_boxplot(width = 0.4)+
  geom_point(size = 2.5, alpha = 0.8)+
  scale_x_discrete(name = expression("Temperature " ( degree*C)))+
   scale_color_manual(values = c("#C6DBEF", "#6BAED6","#2171B5", "#08306B"))+
  ylab(expression(paste('MMR '(mg*O[2] * kg^-1 * min^-1))))+
  scale_y_continuous(limits= c(0, 20))+
  theme_classic()+
  theme(text =element_text(size=18, colour= 'black'),
        axis.text = element_text(size=18, colour= 'black'),
        aspect.ratio = 0.9, legend.position = "none")

#Step 3: Statistics to test for differences in MMR between temperatures

qqPlot(MMR_NU$mmr_scaled_74)

#normal distribution

leveneTest(mmr_scaled_74~as.factor(temperature), data = MMR_NU)

#equal variance

NU_MMR_aov <- aov(mmr_scaled_74~as.factor(temperature), data = MMR_NU)
summary(NU_MMR_aov)

#MMR is not statistically different between 16, 19, 22, and 25

```

Siletz
```{r}
#Step 1: read in MMR data, get means & SEMs
MMR_S <- read_csv("MMR_Siletz.csv")

MMR_S_sum <- MMR_S %>% 
  group_by(temperature) %>% 
  summarise(mean_MMR = mean(mmr_scaled_74), sem_MMR = sd(mmr_scaled_74)/sqrt(n()))

#Step 2: plot MMR data

ggplot(MMR_S, aes(x = as.factor(temperature) , y = mmr_scaled_74, color = as.factor(temperature))) +
  geom_boxplot(width = 0.4)+
  geom_point(size = 2.5, alpha = 0.8)+
  scale_x_discrete(name = expression("Temperature " ( degree*C)))+
   scale_color_manual(values = c("#CCECE6",  "#66C2A4","#238B45", "#00441B"))+
  ylab(expression(paste('MMR '(mg*O[2] * kg^-1 * min^-1))))+
  scale_y_continuous(limits= c(0, 20))+
  theme_classic()+
  theme(text =element_text(size=18, colour= 'black'),
        axis.text = element_text(size=18, colour= 'black'),
        aspect.ratio = 0.9, legend.position = "none")

#Step 3: Statistics to test for differences in MMR between temperatures

qqPlot(MMR_S$mmr_scaled_74)

#not a normal distribution

leveneTest(mmr_scaled_74~as.factor(temperature), data = MMR_S)

#equal variance

S_MMR_aov <- aov(mmr_scaled_74~as.factor(temperature), data = MMR_S)
summary(S_MMR_aov)

#MMR is not statistically different between 16, 19, 22, and 25
```



#### Aerobic Scope - Absolulte (AAS) and Factorial (FAS)

Lower Deschutes 
```{r}
#Step 1: read in data get means and SEMs
AS_LD <- read_csv("Aerobic_Scopes.csv") %>% 
  filter(population=="Lower Deschutes")

AS_LD_sum <- AS_LD %>% 
  group_by(population,temp) %>% 
  summarise(mean_aas = mean(aas), min_aas = min(aas), sem_aas = sd(aas/sqrt(n())), mean_fas = mean(fas), sem_fas = sd(fas)/sqrt(n()), mean_MMR = mean(mmr_scaled), sem_MMR = sd(mmr_scaled)/sqrt(n()), mean_RMR = mean(rmr_scaled), sem_RMR = sd(rmr_scaled)/sqrt(n()), n = n(), min_bw=min(bw)*1000, max_bw=max(bw)*1000)

#Step 2: Plot MMR and RMR 

#MMR and RMR
ggplot(AS_LD_sum)+
  geom_pointrange(aes(x = temp, y = mean_MMR, ymin = mean_MMR-sem_MMR, ymax = mean_MMR+sem_MMR, col = as.factor(temp)), size = 1.5, shape = "triangle")+
   geom_pointrange(aes(x = temp, y = mean_RMR, ymin = mean_RMR-sem_RMR, ymax = mean_RMR+sem_RMR, col = as.factor(temp)), size = 1.5)+
  geom_point(data = AS_LD, aes(y = mmr_scaled, x = temp, col = as.factor(temp)),size =2, alpha = 0.6, shape = "triangle")+
  geom_point(data = AS_LD, aes(y = rmr_scaled, x = temp, col = as.factor(temp)),size =2, alpha = 0.6)+
  scale_color_manual(values = c("#FEE391", "#EC7014" ,"#993404"))+
   scale_x_continuous(name = expression("Temperature " ( degree*C)), limits = c(16, 28), breaks = c(16, 19, 22, 25, 28))+
  scale_y_continuous(limits = c(0,20), breaks = c(0, 5, 10, 15, 20))+
  ylab(expression(paste('Metabolic Rate '(mg*O[2] * kg^-1 * min^-1))))+
  theme_classic()+
  theme(text =element_text(size=20, colour= 'black'),
        axis.text = element_text(size=20, colour= 'black'),
        aspect.ratio = 1, legend.position = "none")

ggsave("Figure5A.png", dpi=300)

#Step 3: Absolute Aerobic Scope (AAS)

#Statistics : Anova
#check assumptions
ggplot(AS_LD, aes(sample = aas))+
  geom_qq()

shapiro.test(AS_LD$aas)

#data are normally distributed 

leveneTest(aas~as.factor(temp), data = AS_LD)

#variance is equal

summary(aov(aas~as.factor(temp), data =AS_LD))

#aas not significantly different between temperatures

#Statistics: polynomial regression

lm_LD_1 <- lm(aas~poly(temp, degree = 1, raw = T), data = AS_LD)

summary(lm_LD_1) #not significant

lm_LD_2 <- lm(aas~poly(temp, degree = 2, raw = T), data = AS_LD)

summary(lm_LD_2) #not significant



#Plot
ggplot(AS_LD, aes(y = aas, x = temp))+
  geom_pointrange(data=AS_LD_sum, aes(x = temp, y = mean_aas, ymin = mean_aas-sem_aas, ymax = mean_aas+sem_aas, col = as.factor(temp)), size = 1.5)+
  geom_point(aes(col = as.factor(temp)),size =2, alpha = 0.5)+
   scale_color_manual(values = c( "#FEE391", "#EC7014" ,"#993404"))+
   scale_x_continuous(name = expression("Temperature " ( degree*C)), limits = c(14, 27), breaks = c(14,16, 18, 20, 22, 24, 26))+
   scale_y_continuous( breaks = c(4,8,12,16))+
   coord_cartesian(ylim = c(1.7, 18))+
   ylab(expression(paste('Absolute Aerobic Scope '(mg*O[2] * kg^-1 * min^-1))))+
  theme_classic()+
  theme(text =element_text(size=20, colour= 'black'),
        axis.text = element_text(size=20, colour= 'black'),
        aspect.ratio = 1, legend.position = "none")

ggsave("Figure6A.png", dpi=300)

#Step 4: Factorial Aerobic Scope (FAS)

#Statistics: linear regression
lm_FAS_LD <- lm(fas~temp, data =AS_LD)

plot(lm_FAS_LD) 

summary(lm_FAS_LD) #FAS=3 at 24.35
 
#Plot
ggplot(AS_LD, aes(y = fas, x = temp))+
  geom_pointrange(data=AS_LD_sum, aes(x = temp, y = mean_fas, ymin = mean_fas-sem_fas, ymax = mean_fas+sem_fas, col = as.factor(temp)), size = 1.5)+
  geom_point(aes(col = as.factor(temp)),size =2, alpha = 0.5)+
   scale_color_manual(values = c( "#FEE391", "#EC7014" ,"#993404"))+
  geom_smooth(method = "lm", se= FALSE, formula = y~x, color ="#EC7014" )+
  stat_regline_equation(label.y = 9, aes(label = ..eq.label..),size=7)+
  stat_regline_equation(label.y = 8.5, aes(label = ..rr.label..),size=7)+
 # geom_abline(slope = coef(lm_FAS_Steamboat)[["Temp"]],intercept = coef(lm_FAS_Steamboat)[["(Intercept)"]], size = 0.7, color = "#2171B5")+
   scale_x_continuous(name = expression("Temperature " ( degree*C)), limits = c(14, 27), breaks = c(14,16, 18, 20, 22, 24, 26))+
 scale_y_continuous(breaks = c(2, 4, 6, 8))+
  coord_cartesian(ylim = c(1,9))+
  ylab(expression(paste('Factorial Aerobic Scope ')))+
   geom_hline(yintercept = 3, linetype = "dashed")+
  theme_classic()+
  theme(text =element_text(size=20, colour= 'black'),
        axis.text = element_text(size=20, colour= 'black'),
        aspect.ratio = 1, legend.position = "none")


ggsave("Figure8A.png", dpi=300)
```
John Day
```{r}
#Step 1: read in data get means and SEMs
AS_JD <- read_csv("Aerobic_Scopes.csv") %>% 
  filter(population=="John Day")

AS_JD_sum <- AS_JD %>% 
  group_by(population,temp) %>% 
  summarise(mean_aas = mean(aas), min_aas = min(aas), sem_aas = sd(aas/sqrt(n())), mean_fas = mean(fas), sem_fas = sd(fas)/sqrt(n()), mean_MMR = mean(mmr_scaled), sem_MMR = sd(mmr_scaled)/sqrt(n()), mean_RMR = mean(rmr_scaled), sem_RMR = sd(rmr_scaled)/sqrt(n()), n = n(), min_bw=min(bw)*1000, max_bw=max(bw)*1000)

#Step 2: Plot MMR and RMR 

#MMR and RMR
ggplot(AS_JD_sum)+
  geom_pointrange(aes(x = temp, y = mean_MMR, ymin = mean_MMR-sem_MMR, ymax = mean_MMR+sem_MMR, col = as.factor(temp)), size = 1.5, shape = "triangle")+
   geom_pointrange(aes(x = temp, y = mean_RMR, ymin = mean_RMR-sem_RMR, ymax = mean_RMR+sem_RMR, col = as.factor(temp)), size = 1.5)+
  geom_point(data = AS_JD, aes(y = mmr_scaled, x = temp, col = as.factor(temp)),size =2, alpha = 0.6, shape = "triangle")+
  geom_point(data = AS_JD, aes(y = rmr_scaled, x = temp, col = as.factor(temp)),size =2, alpha = 0.6)+
  scale_color_manual(values = c("#FCC5C0", "#DD3497", "#980043"))+
   scale_x_continuous(name = expression("Temperature " ( degree*C)), limits = c(16, 28), breaks = c(16, 19, 22, 25, 28))+
  scale_y_continuous(limits = c(0,20), breaks = c(0, 5, 10, 15, 20))+
  ylab(expression(paste('Metabolic Rate '(mg*O[2] * kg^-1 * min^-1))))+
  theme_classic()+
  theme(text =element_text(size=20, colour= 'black'),
        axis.text = element_text(size=20, colour= 'black'),
        aspect.ratio = 1, legend.position = "none")

ggsave("Figure5B.png", dpi=300)

#Step 3: Absolute Aerobic Scope (AAS)

#Statistics : Anova
#check assumptions
ggplot(AS_JD, aes(sample = aas))+
  geom_qq()

shapiro.test(AS_JD$aas)

#data are normally distributed 

leveneTest(aas~as.factor(temp), data = AS_JD)

#variance is equal

summary(aov(aas~as.factor(temp), data =AS_JD))
TukeyHSD(aov(aas~as.factor(temp), data =AS_JD))

#aas is significantly lower at 27C

#Statistics: polynomial regression

lm_JD_1 <- lm(aas~temp, data = AS_JD)

lm_JD_2 <- lm(aas~poly(temp, degree = 2, raw = T), data = AS_JD)


BIC(lm_JD_1, lm_JD_2) #second one is marginally better and has a higher R^2

summary(lm_JD_2) 

#Plot
ggplot(AS_JD, aes(y = aas, x = temp))+
  geom_pointrange(data=AS_JD_sum, aes(x = temp, y = mean_aas, ymin = mean_aas-sem_aas, ymax = mean_aas+sem_aas, col = as.factor(temp)), size = 1.5)+
  geom_point(aes(col = as.factor(temp)),size =2, alpha = 0.5)+
  stat_smooth(method = "lm", se= FALSE, formula = y~poly(x,2, raw=T), color ="#DD3497")+
  geom_segment(aes(x= 21.26, y=10.6,xend =21.26,yend=11.5),color ="black")+
    geom_segment(aes(x= 25.51, y=8,xend =25.51,yend=8.9),color ="black")+
  stat_regline_equation(formula = y~poly(x,2, raw=T), aes(label = ..eq.label..), label.y = 18,size=7)+
  stat_regline_equation(formula = y~poly(x,2, raw=T), aes(label = ..rr.label..), label.y = 17,size=7)+
   scale_color_manual(values = c("#FCC5C0", "#DD3497", "#980043"))+
   scale_x_continuous(name = expression("Temperature " ( degree*C)), limits = c(14, 27), breaks = c(14,16, 18, 20, 22, 24, 26))+
   scale_y_continuous( breaks = c(4,8,12,16))+
   coord_cartesian(ylim = c(1.7, 18))+
   ylab(expression(paste('Absolute Aerobic Scope '(mg*O[2] * kg^-1 * min^-1))))+
  theme_classic()+
  theme(text =element_text(size=20, colour= 'black'),
        axis.text = element_text(size=20, colour= 'black'),
        aspect.ratio = 1, legend.position = "none")

ggsave("Figure6B.png", dpi=300)

#Step 4: Factorial Aerobic Scope (FAS)

#Statistics: linear regression
lm_FAS_JD <- lm(fas~temp, data =AS_JD)

plot(lm_FAS_JD) 

summary(lm_FAS_JD) #FAS=3 at 24.35
 
#Plot
ggplot(AS_JD, aes(y = fas, x = temp))+
  geom_pointrange(data=AS_JD_sum, aes(x = temp, y = mean_fas, ymin = mean_fas-sem_fas, ymax = mean_fas+sem_fas, col = as.factor(temp)), size = 1.5)+
  geom_point(aes(col = as.factor(temp)),size =2, alpha = 0.5)+
   scale_color_manual(values = c( "#FCC5C0", "#DD3497", "#980043"))+
  geom_smooth(method = "lm", se= FALSE, formula = y~x, color ="#DD3497" )+
  stat_regline_equation(label.y = 9, aes(label = ..eq.label..),size=7)+
  stat_regline_equation(label.y = 8.5, aes(label = ..rr.label..),size=7)+
 # geom_abline(slope = coef(lm_FAS_Steamboat)[["Temp"]],intercept = coef(lm_FAS_Steamboat)[["(Intercept)"]], size = 0.7, color = "#2171B5")+
   scale_x_continuous(name = expression("Temperature " ( degree*C)), limits = c(14, 27), breaks = c(14,16, 18, 20, 22, 24, 26))+
 scale_y_continuous(breaks = c(2, 4, 6, 8))+
  coord_cartesian(ylim = c(1,9))+
  ylab(expression(paste('Factorial Aerobic Scope ')))+
   geom_hline(yintercept = 3, linetype = "dashed")+
  theme_classic()+
  theme(text =element_text(size=20, colour= 'black'),
        axis.text = element_text(size=20, colour= 'black'),
        aspect.ratio = 1, legend.position = "none")


ggsave("Figure8B.png", dpi=300)

```
North Umpqua
```{r}
#Step 1: read in data get means and SEMs
AS_NU <- read_csv("Aerobic_Scopes.csv") %>% 
  filter(population=="North Umpqua")

AS_NU_sum <- AS_NU %>% 
  group_by(population,temp) %>% 
  summarise(mean_aas = mean(aas), min_aas = min(aas), sem_aas = sd(aas/sqrt(n())), mean_fas = mean(fas), sem_fas = sd(fas)/sqrt(n()), mean_MMR = mean(mmr_scaled), sem_MMR = sd(mmr_scaled)/sqrt(n()), mean_RMR = mean(rmr_scaled), sem_RMR = sd(rmr_scaled)/sqrt(n()), n = n(), min_bw=min(bw)*1000, max_bw=max(bw)*1000)

#Step 2: Plot MMR and RMR 

#MMR and RMR
ggplot(AS_NU_sum)+
  geom_pointrange(aes(x = temp, y = mean_MMR, ymin = mean_MMR-sem_MMR, ymax = mean_MMR+sem_MMR, col = as.factor(temp)), size = 1.5, shape = "triangle")+
   geom_pointrange(aes(x = temp, y = mean_RMR, ymin = mean_RMR-sem_RMR, ymax = mean_RMR+sem_RMR, col = as.factor(temp)), size = 1.5)+
  geom_point(data = AS_NU, aes(y = mmr_scaled, x = temp, col = as.factor(temp)),size =2, alpha = 0.6, shape = "triangle")+
  geom_point(data = AS_NU, aes(y = rmr_scaled, x = temp, col = as.factor(temp)),size =2, alpha = 0.6)+
  scale_color_manual(values = c("#C6DBEF", "#6BAED6","#2171B5", "#08306B"))+
   scale_x_continuous(name = expression("Temperature " ( degree*C)), limits = c(16, 28), breaks = c(16, 19, 22, 25, 28))+
  scale_y_continuous(limits = c(0,20), breaks = c(0, 5, 10, 15, 20))+
  ylab(expression(paste('Metabolic Rate '(mg*O[2] * kg^-1 * min^-1))))+
  theme_classic()+
  theme(text =element_text(size=20, colour= 'black'),
        axis.text = element_text(size=20, colour= 'black'),
        aspect.ratio = 1, legend.position = "none")

ggsave("Figure5C.png", dpi=300)

#Step 3: Absolute Aerobic Scope (AAS)

#Statistics : Anova
#check assumptions
ggplot(AS_NU,aes(sample = aas))+
  geom_qq()

shapiro.test(AS_NU$aas)

#data are normally distributed 

leveneTest(aas~as.factor(temp), data = AS_NU)

#variance is equal

summary(aov(aas~as.factor(temp), data =AS_NU))
TukeyHSD(aov(aas~as.factor(temp), data =AS_NU))

#aas is significantly lower at 25C compared to 16C and 19C

#Statistics: polynomial regression

lm_NU_1 <- lm(aas~temp, data = AS_NU)

lm_NU_2 <- lm(aas~poly(temp, degree = 2, raw = T), data = AS_NU)


BIC(lm_NU_1, lm_NU_2) #first is marginally better but second has a higher R^2

summary(lm_NU_2) 

#Plot
ggplot(AS_NU, aes(y = aas, x = temp))+
  geom_pointrange(data=AS_NU_sum, aes(x = temp, y = mean_aas, ymin = mean_aas-sem_aas, ymax = mean_aas+sem_aas, col = as.factor(temp)), size = 1.5)+
  geom_point(aes(col = as.factor(temp)),size =2, alpha = 0.5)+
  stat_smooth(method = "lm", se= FALSE, formula = y~poly(x,2, raw=T), color ="#2171B5")+
    geom_segment(aes(x= 23.7, y=5.9,xend =23.7,yend=6.8),color ="black")+
  geom_segment(aes(x= 17.4, y=7.4,xend =17.4,yend=8.3),color ="black")+
  stat_regline_equation(formula = y~poly(x,2, raw=T), aes(label = ..eq.label..), label.y = 18,size=7)+
  stat_regline_equation(formula = y~poly(x,2, raw=T), aes(label = ..rr.label..), label.y = 17,size=7)+
   scale_color_manual(values = c("#C6DBEF", "#6BAED6","#2171B5", "#08306B"))+
   scale_x_continuous(name = expression("Temperature " ( degree*C)), limits = c(14, 27), breaks = c(14,16, 18, 20, 22, 24, 26))+
   scale_y_continuous( breaks = c(4,8,12,16))+
   coord_cartesian(ylim = c(1.7, 18))+
   ylab(expression(paste('Absolute Aerobic Scope '(mg*O[2] * kg^-1 * min^-1))))+
  theme_classic()+
  theme(text =element_text(size=20, colour= 'black'),
        axis.text = element_text(size=20, colour= 'black'),
        aspect.ratio = 1, legend.position = "none")

ggsave("Figure6C.png", dpi=300)

#Step 4: Factorial Aerobic Scope (FAS)

#Statistics: linear regression
lm_FAS_NU <- lm(fas~temp, data =AS_NU)

plot(lm_FAS_NU) 

summary(lm_FAS_NU) #FAS=3 at 24.35
 
#Plot
ggplot(AS_NU, aes(y = fas, x = temp))+
  geom_pointrange(data=AS_NU_sum, aes(x = temp, y = mean_fas, ymin = mean_fas-sem_fas, ymax = mean_fas+sem_fas, col = as.factor(temp)), size = 1.5)+
  geom_point(aes(col = as.factor(temp)),size =2, alpha = 0.5)+
   scale_color_manual(values = c("#C6DBEF", "#6BAED6","#2171B5", "#08306B"))+
  geom_smooth(method = "lm", se= FALSE, formula = y~x, color ="#2171B5" )+
  stat_regline_equation(label.y = 9, aes(label = ..eq.label..),size=7)+
  stat_regline_equation(label.y = 8.5, aes(label = ..rr.label..),size=7)+
 # geom_abline(slope = coef(lm_FAS_Steamboat)[["Temp"]],intercept = coef(lm_FAS_Steamboat)[["(Intercept)"]], size = 0.7, color = "#2171B5")+
   scale_x_continuous(name = expression("Temperature " ( degree*C)), limits = c(14, 27), breaks = c(14,16, 18, 20, 22, 24, 26))+
 scale_y_continuous(breaks = c(2, 4, 6, 8))+
  coord_cartesian(ylim = c(1,9))+
  ylab(expression(paste('Factorial Aerobic Scope ')))+
   geom_hline(yintercept = 3, linetype = "dashed")+
  theme_classic()+
  theme(text =element_text(size=20, colour= 'black'),
        axis.text = element_text(size=20, colour= 'black'),
        aspect.ratio = 1, legend.position = "none")


ggsave("Figure8C.png", dpi=300)
```
Siletz
```{r}
#Step 1: read in data get means and SEMs
AS_S <- read_csv("Aerobic_Scopes.csv") %>% 
  filter(population=="Siletz")

AS_S_sum <- AS_S %>% 
  group_by(population,temp) %>% 
  summarise(mean_aas = mean(aas), min_aas = min(aas), sem_aas = sd(aas/sqrt(n())), mean_fas = mean(fas), sem_fas = sd(fas)/sqrt(n()), mean_MMR = mean(mmr_scaled), sem_MMR = sd(mmr_scaled)/sqrt(n()), mean_RMR = mean(rmr_scaled), sem_RMR = sd(rmr_scaled)/sqrt(n()), n = n(), min_bw=min(bw)*1000, max_bw=max(bw)*1000)

#Step 2: Plot MMR and RMR 

#MMR and RMR
ggplot(AS_S_sum)+
  geom_pointrange(aes(x = temp, y = mean_MMR, ymin = mean_MMR-sem_MMR, ymax = mean_MMR+sem_MMR, col = as.factor(temp)), size = 1.5, shape = "triangle")+
   geom_pointrange(aes(x = temp, y = mean_RMR, ymin = mean_RMR-sem_RMR, ymax = mean_RMR+sem_RMR, col = as.factor(temp)), size = 1.5)+
  geom_point(data = AS_S, aes(y = mmr_scaled, x = temp, col = as.factor(temp)),size =2, alpha = 0.6, shape = "triangle")+
  geom_point(data = AS_S, aes(y = rmr_scaled, x = temp, col = as.factor(temp)),size =2, alpha = 0.6)+
  scale_color_manual(values = c("#CCECE6",  "#66C2A4","#238B45", "#00441B"))+
   scale_x_continuous(name = expression("Temperature " ( degree*C)), limits = c(16, 28), breaks = c(16, 19, 22, 25, 28))+
  scale_y_continuous(limits = c(0,20), breaks = c(0, 5, 10, 15, 20))+
  ylab(expression(paste('Metabolic Rate '(mg*O[2] * kg^-1 * min^-1))))+
  theme_classic()+
  theme(text =element_text(size=20, colour= 'black'),
        axis.text = element_text(size=20, colour= 'black'),
        aspect.ratio = 1, legend.position = "none")

ggsave("Figure5D.png", dpi=300)

#Step 3: Absolute Aerobic Scope (AAS)

#Statistics : Anova
#check assumptions
ggplot(AS_S,aes(sample = aas))+
  geom_qq()

shapiro.test(AS_S$aas)

#data are normally distributed 

leveneTest(aas~as.factor(temp), data = AS_S)

#variance is equal

summary(aov(aas~as.factor(temp), data =AS_S))
TukeyHSD(aov(aas~as.factor(temp), data =AS_S))

#aas is significantly lower at 25C compared to 16C and 19C

#Statistics: polynomial regression

lm_S_1 <- lm(aas~temp, data = AS_S)

lm_S_2 <- lm(aas~poly(temp, degree = 2, raw = T), data = AS_S)


BIC(lm_S_1, lm_S_2) #second is marginally better and has a higher R^2

summary(lm_S_2) 

#Plot
ggplot(AS_S, aes(y = aas, x = temp))+
  geom_pointrange(data=AS_S_sum, aes(x = temp, y = mean_aas, ymin = mean_aas-sem_aas, ymax = mean_aas+sem_aas, col = as.factor(temp)), size = 1.5)+
  geom_point(aes(col = as.factor(temp)),size =2, alpha = 0.5)+
  stat_smooth(method = "lm", se= FALSE, formula = y~poly(x,2, raw=T), color ="#238B45")+
    geom_segment(aes(x= 17.89, y=10.5,xend =17.89,yend=11.4),color ="black")+
    geom_segment(aes(x= 22.7, y=8.3,xend =22.7,yend=9.2),color ="black")+
  stat_regline_equation(formula = y~poly(x,2, raw=T), aes(label = ..eq.label..), label.y = 18,size=7)+
  stat_regline_equation(formula = y~poly(x,2, raw=T), aes(label = ..rr.label..), label.y = 17,size=7)+
   scale_color_manual(values = c("#CCECE6",  "#66C2A4","#238B45", "#00441B"))+
   scale_x_continuous(name = expression("Temperature " ( degree*C)), limits = c(14, 27), breaks = c(14,16, 18, 20, 22, 24, 26))+
   scale_y_continuous( breaks = c(4,8,12,16))+
   coord_cartesian(ylim = c(1.7, 18))+
   ylab(expression(paste('Absolute Aerobic Scope '(mg*O[2] * kg^-1 * min^-1))))+
  theme_classic()+
  theme(text =element_text(size=20, colour= 'black'),
        axis.text = element_text(size=20, colour= 'black'),
        aspect.ratio = 1, legend.position = "none")

ggsave("Figure6D.png", dpi=300)

#Step 4: Factorial Aerobic Scope (FAS)

#Statistics: linear regression
lm_FAS_S <- lm(fas~temp, data =AS_S)

plot(lm_FAS_S) 

shapiro.test(resid(lm_FAS_S))#residuals normally distributed

summary(lm_FAS_NU) #FAS=3 at 24.35
 
#Plot
ggplot(AS_NU, aes(y = fas, x = temp))+
  geom_pointrange(data=AS_NU_sum, aes(x = temp, y = mean_fas, ymin = mean_fas-sem_fas, ymax = mean_fas+sem_fas, col = as.factor(temp)), size = 1.5)+
  geom_point(aes(col = as.factor(temp)),size =2, alpha = 0.5)+
   scale_color_manual(values = c("#CCECE6",  "#66C2A4","#238B45", "#00441B"))+
  geom_smooth(method = "lm", se= FALSE, formula = y~x, color ="#238B45" )+
  stat_regline_equation(label.y = 9, aes(label = ..eq.label..),size=7)+
  stat_regline_equation(label.y = 8.5, aes(label = ..rr.label..),size=7)+
   scale_x_continuous(name = expression("Temperature " ( degree*C)), limits = c(14, 27), breaks = c(14,16, 18, 20, 22, 24, 26))+
 scale_y_continuous(breaks = c(2, 4, 6, 8))+
  coord_cartesian(ylim = c(1,9))+
  ylab(expression(paste('Factorial Aerobic Scope ')))+
   geom_hline(yintercept = 3, linetype = "dashed")+
  theme_classic()+
  theme(text =element_text(size=20, colour= 'black'),
        axis.text = element_text(size=20, colour= 'black'),
        aspect.ratio = 1, legend.position = "none")


ggsave("Figure8D.png", dpi=300)
```

Population Comparisons 




