---
title: "3_Exercise_Recovery_Analysis"
author: "Terra Dressler"
date: "2024-05-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

### Libraries
```{r}

library(tidyverse)
library(ggbreak)
library(lme4)
library(car)
library(ggpubr)

```

### Recovery of Metabolic Rate (MO2)

Siletz
```{r}

#Load Recovery Data
recov_S <- read_csv("Recovery_Siletz.csv") %>% 
  mutate(time_round = round(min_start_real, -1),  percent_mmr = percent_mmr*100, mmr_50 = mmr/2, temp = as.factor(temp))

#Plot Mo2 over time for each fish
ggplot(recov_S, aes(x = min_start_real, y = mo2_scaled, color = temp))+
  geom_point(size = 2.5, alpha = 0.8)+
  scale_color_manual(values = c("#CCECE6",  "#66C2A4","#238B45", "#00441B"))+
  #geom_line(aes(sep = ID))+
  labs(x = "Time Post-Chase (min)")+
  theme_classic()

#This is a bi-exponential decay and we need to model both exponential functions (decay between the first 2 time points and then the rest)

#Second exponential decay

recov_S_B <- recov_S%>%
  filter(time_round>11) 

ggplot(recov_S_B, aes(y = ln_mo2_minus_rmr, x = min_start_real, col = temp))+
geom_point(size = 2.5, alpha = 0.8)+
  scale_color_manual(values = c("#CCECE6",  "#66C2A4","#238B45", "#00441B"))+
#  geom_line()+
 # geom_line(aes(sep = ID))+
  labs(x = "Time Post-Chase", y = "ln(MO2-RMR)")+
# stat_smooth(method = "lm", se=FALSE)+
 # stat_cor(label.x = 15)+
  theme_classic()+
  theme(legend.position = "none")

lm_B <- lm( ln_mo2_minus_rmr~min_start_real, data = recov_S_B)
lm_B_T <- lm( ln_mo2_minus_rmr~min_start_real + temp, data = recov_S_B)
lm_B_ID <- lm( ln_mo2_minus_rmr~min_start_real + ID, data = recov_S_B)
lm_B_T2 <- lm( ln_mo2_minus_rmr~min_start_real * temp, data = recov_S_B)
lm_B_ID2 <- lm( ln_mo2_minus_rmr~min_start_real * ID, data = recov_S_B)

lmer_B <- lmer(ln_mo2_minus_rmr~min_start_real+(1|ID), data = recov_S_B)
lmer_B_T <- lmer( ln_mo2_minus_rmr~min_start_real+temp+(1|ID), data = recov_S_B)

BIC(lm_B, lm_B_T, lm_B_ID, lm_B_T2, lm_B_ID2, lmer_B,lmer_B_T)

#Best fit includes ID as a fixed or random effect and does NOT include temperature
#Realistically we do not have enough data points to model recovery for each fish (i.e., to have ID be a fixed effect) although this would be ideal
#Mixed model using ID as a random effect fits just as well according to BIC

summary(lmer_B)

plot(lmer_B)
hist(resid(lmer_B))

#first  decay
recov_S_A <- recov_S %>%
  filter(time_round<11) %>% 
  na.omit()

ggplot(recov_S_A, aes(y = ln_mo2_minus_Bebt, x = min_start_real, col = temp))+
  scale_color_manual(values = c("#CCECE6",  "#66C2A4","#238B45", "#00441B"))+
  geom_point(alpha = 0.6, size = 2.5)+
  stat_smooth(se=FALSE, method = "lm")+
  stat_cor()+
  theme_classic()

lm_A <- lm(ln_mo2_minus_Bebt~min_start_real, data = recov_S_A)
lm_A_T <- lm(ln_mo2_minus_Bebt~min_start_real + temp, data = recov_S_A)
lm_A_T2 <- lm(ln_mo2_minus_Bebt~min_start_real * temp, data = recov_S_A)
lm_A_ID <- lm(ln_mo2_minus_Bebt~min_start_real + ID, data = recov_S_A)
lm_A_ID2 <- lm(ln_mo2_minus_Bebt~min_start_real * ID, data = recov_S_A)

lmer_A <- lmer(ln_mo2_minus_Bebt~min_start_real + (1|ID), data = recov_S_A)

BIC(lm_A, lm_A_T, lm_A_T2, lm_A_ID, lm_A_ID2, lmer_A)

Anova(lm_A_T)

summary(lm_A_T)

qqPlot(resid(lm_A_T2))
```




### Recovery of Factorial Aerobic Scope

Lower Deschutes
```{r}

recov_LD <- read_csv("Recovery_LowerDeschutes.csv") %>% 
  mutate(time_round = round(min_start_real, -1),  percent_mmr = percent_mmr*100, mmr_50 = mmr/2, temp = as.factor(temp))

recov_LD_sum <- recov_LD %>% 
    group_by(temp, time_round) %>% 
  summarise(mean_mo2 = mean(mo2_scaled), sd_mo2 = sd(mo2_scaled), sem_mo2 = sd_mo2/sqrt(n()), mean_percent = mean(percent_mmr), sd_percent= sd(percent_mmr), sem_percent = sd_percent/sqrt(n()), n = n(), mean_aas = mean(percent_aas), sem_aas = sd(percent_aas)/sqrt(n()),mean_fas = mean(fas_available), sem_fas = sd(fas_available)/sqrt(n()),n = n()) %>% 
  filter(n>2)

fas_max_LD <- read_csv("fas_max_LD.csv") %>% 
  group_by(temp, time_round) %>% 
  summarise(mean_fas = mean(fas_available), sem_fas = sd(fas_available)/sqrt(n()), n = n())

ggplot(recov_LD_sum, aes(x = time_round, y = mean_fas, ymin = mean_fas-sem_fas, ymax = mean_fas+sem_fas, color = as.factor(temp)))+
  geom_pointrange(size = .8, alpha = .7)+
  geom_pointrange(data = fas_max_LD, aes(x = time_round, y=mean_fas, ymin = mean_fas-sem_fas, ymax = mean_fas+sem_fas, color = as.factor(temp)),size = .8, alpha = .7)+
  scale_color_manual(values = c("#FEE391", "#EC7014" ,"#993404"))+
  geom_line(size =.7)+
  labs(y = "FAS Available", x = "Time Post-MMR (minutes)")+
  scale_y_continuous(limits = c(1,7.5),breaks =c(1,3,5,7))+
  scale_x_cut(breaks = c(62),which=c(2), space = c(.5), scales =c(0.1))+
  geom_hline(aes(yintercept = 3), linetype = "dashed")+
  scale_x_continuous(limits=c(-1.5,68), breaks = c(-0,20,40,60))+
  theme_classic()+
  theme(axis.text = element_text(size = 18),
        axis.title  = element_text(size=18),
        legend.text=element_text(size=18),
        legend.title = element_blank())

ggsave("Figure10A.png",height =5,width=7.5, dpi=300)
```

John Day
```{r}

recov_JD <- read_csv("Recovery_JohnDay.csv") %>% 
  mutate(time_round = round(min_start_real, -1),  percent_mmr = percent_mmr*100, mmr_50 = mmr/2, temp = as.factor(temp))

recov_JD_sum <- recov_JD %>% 
    group_by(temp, time_round) %>% 
  summarise(mean_mo2 = mean(mo2_scaled), sd_mo2 = sd(mo2_scaled), sem_mo2 = sd_mo2/sqrt(n()), mean_percent = mean(percent_mmr), sd_percent= sd(percent_mmr), sem_percent = sd_percent/sqrt(n()), n = n(), mean_aas = mean(percent_aas), sem_aas = sd(percent_aas)/sqrt(n()),mean_fas = mean(fas_available), sem_fas = sd(fas_available)/sqrt(n()),n = n()) %>% 
  filter(n>2)

fas_max_JD <- read_csv("fas_max_JD.csv") %>% 
  group_by(temp, time_round) %>% 
  summarise(mean_fas = mean(fas_available), sem_fas = sd(fas_available)/sqrt(n()), n = n())

ggplot(recov_JD_sum, aes(x = time_round, y = mean_fas, ymin = mean_fas-sem_fas, ymax = mean_fas+sem_fas, color = as.factor(temp)))+
  geom_pointrange(size = .8, alpha = .7)+
  geom_pointrange(data = fas_max_JD, aes(x = time_round, y=mean_fas, ymin = mean_fas-sem_fas, ymax = mean_fas+sem_fas, color = as.factor(temp)),size = .8, alpha = .7)+
  scale_color_manual(values = c("#FCC5C0", "#DD3497", "#980043"))+
  geom_line(size =.7)+
  labs(y = "FAS Available", x = "Time Post-MMR (minutes)")+
  scale_y_continuous(limits = c(1,7.5),breaks =c(1,3,5,7))+
  scale_x_cut(breaks = c(62),which=c(2), space = c(.5), scales =c(0.1))+
  geom_hline(aes(yintercept = 3), linetype = "dashed")+
  scale_x_continuous(limits=c(-1.5,68), breaks = c(-0,20,40,60))+
  theme_classic()+
  theme(axis.text = element_text(size = 18),
        axis.title  = element_text(size=18),
        legend.text=element_text(size=18),
        legend.title = element_blank())

ggsave("Figure10B.png",height =5,width=7.5, dpi=300)

```

North Umpqua
```{r}

recov_NU <- read_csv("Recovery_NorthUmpqua.csv") %>% 
  mutate(time_round = round(min_start_real, -1),  percent_mmr = percent_mmr*100, mmr_50 = mmr/2, temp = as.factor(temp))

recov_NU_sum <- recov_NU %>% 
    group_by(temp, time_round) %>% 
  summarise(mean_mo2 = mean(mo2_scaled), sd_mo2 = sd(mo2_scaled), sem_mo2 = sd_mo2/sqrt(n()), mean_percent = mean(percent_mmr), sd_percent= sd(percent_mmr), sem_percent = sd_percent/sqrt(n()), n = n(), mean_aas = mean(percent_aas), sem_aas = sd(percent_aas)/sqrt(n()),mean_fas = mean(fas_available), sem_fas = sd(fas_available)/sqrt(n()),n = n()) %>% 
  filter(n>2)

fas_max_NU <- read_csv("fas_max_NU.csv") %>% 
  group_by(temp, time_round) %>% 
  summarise(mean_fas = mean(fas_available), sem_fas = sd(fas_available)/sqrt(n()), n = n())

ggplot(recov_NU_sum, aes(x = time_round, y = mean_fas, ymin = mean_fas-sem_fas, ymax = mean_fas+sem_fas, color = as.factor(temp)))+
  geom_pointrange(size = .8, alpha = .7)+
  geom_pointrange(data = fas_max_NU, aes(x = time_round, y=mean_fas, ymin = mean_fas-sem_fas, ymax = mean_fas+sem_fas, color = as.factor(temp)),size = .8, alpha = .7)+
  scale_color_manual(values = c("#C6DBEF", "#6BAED6","#2171B5", "#08306B"))+
  geom_line(size =.7)+
  labs(y = "FAS Available", x = "Time Post-MMR (minutes)")+
  scale_y_continuous(limits = c(1,7.5),breaks =c(1,3,5,7))+
  scale_x_cut(breaks = c(62),which=c(2), space = c(.5), scales =c(0.1))+
  geom_hline(aes(yintercept = 3), linetype = "dashed")+
  scale_x_continuous(limits=c(-1.5,68), breaks = c(-0,20,40,60))+
  theme_classic()+
  theme(axis.text = element_text(size = 18),
        axis.title  = element_text(size=18),
        legend.text=element_text(size=18),
        legend.title = element_blank())

ggsave("Figure10C.png",height =5,width=7.5, dpi=300)

```

Siletz

```{r}

recov_S <- read_csv("Recovery_Siletz.csv") %>% 
  mutate(time_round = round(min_start_real, -1),  percent_mmr = percent_mmr*100, mmr_50 = mmr/2, temp = as.factor(temp))

recov_S_sum <- recov_S %>% 
    group_by(temp, time_round) %>% 
  summarise(mean_mo2 = mean(mo2_scaled), sd_mo2 = sd(mo2_scaled), sem_mo2 = sd_mo2/sqrt(n()), mean_percent = mean(percent_mmr), sd_percent= sd(percent_mmr), sem_percent = sd_percent/sqrt(n()), n = n(), mean_aas = mean(percent_aas), sem_aas = sd(percent_aas)/sqrt(n()),mean_fas = mean(fas_available), sem_fas = sd(fas_available)/sqrt(n()),n = n()) %>% 
  filter(n>2)

fas_max_S <- read_csv("fas_max_S.csv") %>% 
  group_by(temp, time_round) %>% 
  summarise(mean_fas = mean(fas_available), sem_fas = sd(fas_available)/sqrt(n()), n = n())

ggplot(recov_S_sum, aes(x = time_round, y = mean_fas, ymin = mean_fas-sem_fas, ymax = mean_fas+sem_fas, color = as.factor(temp)))+
  geom_pointrange(size = .8, alpha = .7)+
  geom_pointrange(data = fas_max_S, aes(x = time_round, y=mean_fas, ymin = mean_fas-sem_fas, ymax = mean_fas+sem_fas, color = as.factor(temp)),size = .8, alpha = .7)+
  scale_color_manual(values = c("#CCECE6",  "#66C2A4","#238B45", "#00441B"))+
  geom_line(size =.7)+
  labs(y = "FAS Available", x = "Time Post-MMR (minutes)")+
  scale_y_continuous(limits = c(1,7.5),breaks =c(1,3,5,7))+
  scale_x_cut(breaks = c(62),which=c(2), space = c(.5), scales =c(0.1))+
  geom_hline(aes(yintercept = 3), linetype = "dashed")+
  scale_x_continuous(limits=c(-1.5,68), breaks = c(-0,20,40,60))+
  theme_classic()+
  theme(axis.text = element_text(size = 18),
        axis.title  = element_text(size=18),
        legend.text=element_text(size=18),
        legend.title = element_blank())

ggsave("Figure10D.png",height =5,width=7.5, dpi=300)

```